
services:
  catalog_db:
    container_name: catalog-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=catalog-db
    restart: always
    ports:
      - "7411:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  catalog_api:
    container_name: catalog-api
    build:
      context: ./src/Services/Catalog/Catalog.API
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    ports:
      - "7301:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - catalog_db
    restart: unless-stopped

  basket_db:
    container_name: basket-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=basket-db
    restart: always
    ports:
      - "7102:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  basket_redis:
    container_name: basket-redis
    image: redis:latest
    command: redis-server --requirepass "123456789" --protected-mode no
    restart: always
    ports:
      - "7122:6379"
    volumes:
      - redis_basket:/data

volumes:
  postgres_catalog:
  postgres_basket:
  redis_basket: