
services:
  catalog_db:
    container_name: catalog-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=catalog-db
    restart: always
    ports:
      - "7411:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  catalog_api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: ./dockerfile-catalog
      args:
        - BUILDKIT_INLINE_CACHE=0
    ports:
      - "7301:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # - ConnectionString__PgConnection=...
      # - MediatR__LicenseKey=...
    depends_on:
      - catalog_db
    restart: unless-stopped

volumes:
  postgres_catalog: